### ISSUE TITLE
sqlite3 error on launch

### ISSUE THREAD

**Issue by codeo1io** [Maxence-L/okcupidon#2]
I've setup my config with credentials and the attributes indicated on your page. I'm running python 3.9.6 and getting the following error on launch

% python3 -m okcupidon run    
A new database will be created in ...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/okcupidon/__main__.py", line 207, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/okcupidon/__main__.py", line 122, in main
    okc_db = DataBase(outfile)
  File "/usr/local/lib/python3.9/site-packages/okcupidon/ourdatabase.py", line 34, in __init__
    self.__c.executescript(create_database_script)
sqlite3.OperationalError: near "max": syntax error

**Comment by codeo1io** [comment]
Fixed it by changing "max" to a number
